### PR TITLE
Added parts

### PR DESCRIPTION
**Pull request by mzahm**
I copied all the missing parts of Jean's presentation and modified some. I also added the data frame section with some exercises. If you have time, could you please take a look and merge with main if you agree? Obviously, add things if you want to :)
Thanks!

### CODE REVIEW

**Comment by jmonlong** [comment]
Looks good! I've added a few minor style things and corrected some example code chunks. Looks ready to be merged to me.

**Review by rekren — APPROVED** [review]
Thank you Jean for these fixes.

**Review by rekren — APPROVED** [review]
Thanks Margot, I have also checked and everything seems in order to me.

**Comment by mzahm** [comment]
Thanks for correcting, checking and merging this pull request! We are ready for the next session.

**Pull request merged**
